export const business = {
    "cli": {
        "dps": {
            "Model": {
                "ens": {
                    "magIndex": {
                        "id": "magIndex",
                        "name": "经营指标",
                        "pname": "",
                        "level": 0,
                        "type": "Any",
                        "deviceTypeId": 0,
                        "protocolId": 0,
                        "devicesAmount": 0,
                        "phaseCount": 0,
                        "firstRunStatArr": [],
                        "thirdRunStatArr": [],
                        "standardWtSignStatus": false,
                        "isaccess": 0,
                        "wfMonitorShowMap": false,
                        "proxyPort": 0,
                        "sort": 0,
                        "deviceOrderNum": 0,
                        "resetisview": false,
                        "active": false,
                        "standardWt": false,
                        "antiVortexFlag": false,
                        "locking": false,
                        "multipleAgcOrEms": false
                    }
                },
                "dis": {
                    "hg_any_Profit": {
                        "id": "hg_any_Profit",
                        "name": "利润",
                        "show": true,
                        "pathId": "profit",
                        "unit": "万元",
                        "max": "0.0",
                        "min": "0.0",
                        "place": "2",
                        "packageVO": null,
                        "type": "System.Decimal",
                        "coeff": "1",
                        "toThousand": false,
                        "url": null,
                        "staType": "month",
                        "customAnalysis": false,
                        "remoteSignaling": false,
                        "needToExplain": false,
                        "dataType": "float",
                        "dataflag": null,
                        "sn": "利润",
                        "sort": null,
                        "protocolId": 0,
                        "range": null,
                        "visualIsEnable": false,
                        "visualIsDeleted": false,
                        "visualIecType": null,
                        "visualExpress": null,
                        "visualModifyUserName": null,
                        "visualModifyTime": null,
                        "iecType": 0,
                        "originalIecType": null,
                        "transtype": 0,
                        "trgop": null,
                        "trueValueDesc": null,
                        "falsedValueDesc": null,
                        "visible": true,
                        "advancedControl": false,
                        "visualIec": false
                    },
                    "hg_any_Income": {
                        "id": "hg_any_Income",
                        "name": "收入",
                        "show": true,
                        "pathId": "income",
                        "unit": "万元",
                        "max": "0.0",
                        "min": "0.0",
                        "place": "2",
                        "packageVO": null,
                        "type": "System.Decimal",
                        "coeff": "1",
                        "toThousand": false,
                        "url": null,
                        "staType": "month",
                        "customAnalysis": false,
                        "remoteSignaling": false,
                        "needToExplain": false,
                        "dataType": "float",
                        "dataflag": null,
                        "sn": "收入",
                        "sort": null,
                        "protocolId": 0,
                        "range": null,
                        "visualIsEnable": false,
                        "visualIsDeleted": false,
                        "visualIecType": null,
                        "visualExpress": null,
                        "visualModifyUserName": null,
                        "visualModifyTime": null,
                        "iecType": 0,
                        "originalIecType": null,
                        "transtype": 0,
                        "trgop": null,
                        "trueValueDesc": null,
                        "falsedValueDesc": null,
                        "visible": true,
                        "advancedControl": false,
                        "visualIec": false
                    },
                    "hg_any_Cost": {
                        "id": "hg_any_Cost",
                        "name": "成本",
                        "show": true,
                        "pathId": "cost",
                        "unit": "万元",
                        "max": "0.0",
                        "min": "0.0",
                        "place": "2",
                        "packageVO": null,
                        "type": "System.Decimal",
                        "coeff": "1",
                        "toThousand": false,
                        "url": null,
                        "staType": "month",
                        "customAnalysis": false,
                        "remoteSignaling": false,
                        "needToExplain": false,
                        "dataType": "float",
                        "dataflag": null,
                        "sn": "成本",
                        "sort": null,
                        "protocolId": 0,
                        "range": null,
                        "visualIsEnable": false,
                        "visualIsDeleted": false,
                        "visualIecType": null,
                        "visualExpress": null,
                        "visualModifyUserName": null,
                        "visualModifyTime": null,
                        "iecType": 0,
                        "originalIecType": null,
                        "transtype": 0,
                        "trgop": null,
                        "trueValueDesc": null,
                        "falsedValueDesc": null,
                        "visible": true,
                        "advancedControl": false,
                        "visualIec": false
                    },
                    "hg_any_Profit_all": {
                        "id": "hg_any_Profit_all",
                        "name": "年累计利润",
                        "show": true,
                        "pathId": "",
                        "unit": "万元",
                        "max": "0.0",
                        "min": "0.0",
                        "place": "2",
                        "packageVO": null,
                        "type": "System.Decimal",
                        "coeff": "1",
                        "toThousand": true,
                        "url": null,
                        "staType": "month",
                        "customAnalysis": false,
                        "remoteSignaling": false,
                        "needToExplain": false,
                        "dataType": "float",
                        "dataflag": null,
                        "sn": "年累计利润",
                        "sort": null,
                        "protocolId": 0,
                        "range": null,
                        "visualIsEnable": false,
                        "visualIsDeleted": false,
                        "visualIecType": null,
                        "visualExpress": null,
                        "visualModifyUserName": null,
                        "visualModifyTime": null,
                        "iecType": 0,
                        "originalIecType": null,
                        "transtype": 0,
                        "trgop": null,
                        "trueValueDesc": null,
                        "falsedValueDesc": null,
                        "visible": true,
                        "advancedControl": false,
                        "visualIec": false
                    },
                    "hg_any_Income_all": {
                        "id": "hg_any_Income_all",
                        "name": "年累计收入",
                        "show": true,
                        "pathId": "",
                        "unit": "万元",
                        "max": "0.0",
                        "min": "0.0",
                        "place": "2",
                        "packageVO": null,
                        "type": "System.Decimal",
                        "coeff": "1",
                        "toThousand": true,
                        "url": null,
                        "staType": "month",
                        "customAnalysis": false,
                        "remoteSignaling": false,
                        "needToExplain": false,
                        "dataType": "float",
                        "dataflag": null,
                        "sn": "年累计收入",
                        "sort": null,
                        "protocolId": 0,
                        "range": null,
                        "visualIsEnable": false,
                        "visualIsDeleted": false,
                        "visualIecType": null,
                        "visualExpress": null,
                        "visualModifyUserName": null,
                        "visualModifyTime": null,
                        "iecType": 0,
                        "originalIecType": null,
                        "transtype": 0,
                        "trgop": null,
                        "trueValueDesc": null,
                        "falsedValueDesc": null,
                        "visible": true,
                        "advancedControl": false,
                        "visualIec": false
                    },
                    "hg_any_Cost_all": {
                        "id": "hg_any_Cost_all",
                        "name": "年累计成本",
                        "show": true,
                        "pathId": "",
                        "unit": "万元",
                        "max": "0.0",
                        "min": "0.0",
                        "place": "2",
                        "packageVO": null,
                        "type": "System.Decimal",
                        "coeff": "1",
                        "toThousand": true,
                        "url": null,
                        "staType": "month",
                        "customAnalysis": false,
                        "remoteSignaling": false,
                        "needToExplain": false,
                        "dataType": "float",
                        "dataflag": null,
                        "sn": "年累计成本",
                        "sort": null,
                        "protocolId": 0,
                        "range": null,
                        "visualIsEnable": false,
                        "visualIsDeleted": false,
                        "visualIecType": null,
                        "visualExpress": null,
                        "visualModifyUserName": null,
                        "visualModifyTime": null,
                        "iecType": 0,
                        "originalIecType": null,
                        "transtype": 0,
                        "trgop": null,
                        "trueValueDesc": null,
                        "falsedValueDesc": null,
                        "visible": true,
                        "advancedControl": false,
                        "visualIec": false
                    }
                },
                "dps": {
                    "magIndex": {
                        "show": [
                            "hg_any_Profit",
                            "hg_any_Income",
                            "hg_any_Cost",
                            "hg_any_Profit_all",
                            "hg_any_Income_all",
                            "hg_any_Cost_all"
                        ],
                        "hide": []
                    }
                },
                "pels": {},
                "enids": [
                    "magIndex"
                ],
                "disIds": [
                    "hg_any_Profit",
                    "hg_any_Income",
                    "hg_any_Cost",
                    "hg_any_Profit_all",
                    "hg_any_Income_all",
                    "hg_any_Cost_all"
                ],
                "prs": {},
                "svg": "<svg>\n    <g EntType=\"Any\" RelaDatas=\"snBigScreenMagIndexHG\" show=\"true\"/>\n</svg>",
                "resource": {},
                "data": [
                    {
                        "month": "1",
                        "hg_any_Income": 30449.3229,
                        "hg_any_Profit": 8134.141187,
                        "hg_any_Cost": 15708.59992
                    },
                    {
                        "month": "2",
                        "hg_any_Income": 27134.238651,
                        "hg_any_Profit": 4928.453512,
                        "hg_any_Cost": 15363.132307
                    },
                    {
                        "month": "3",
                        "hg_any_Income": 36399.19123,
                        "hg_any_Profit": 13604.0483934,
                        "hg_any_Cost": 16956.166886
                    },
                    {
                        "month": "4",
                        "hg_any_Income": 36987.969186,
                        "hg_any_Profit": 14492.8464478,
                        "hg_any_Cost": 16389.910313
                    },
                    {
                        "month": "5",
                        "hg_any_Income": 33509.78855,
                        "hg_any_Profit": 11935.89752,
                        "hg_any_Cost": 15651.81523
                    },
                    {
                        "month": "6",
                        "hg_any_Income": 28967.98022,
                        "hg_any_Profit": 6041.450071,
                        "hg_any_Cost": 16234.67838
                    },
                    {
                        "month": "7",
                        "hg_any_Income": 36200.155873,
                        "hg_any_Profit": 10546.826236,
                        "hg_any_Cost": 17858.323087
                    },
                    {
                        "month": "8",
                        "hg_any_Income": 0,
                        "hg_any_Profit": 0,
                        "hg_any_Cost": 0
                    },
                    {
                        "month": "9",
                        "hg_any_Income": 0,
                        "hg_any_Profit": 0,
                        "hg_any_Cost": 0
                    },
                    {
                        "month": "10",
                        "hg_any_Income": 0,
                        "hg_any_Profit": 0,
                        "hg_any_Cost": 0
                    },
                    {
                        "month": "11",
                        "hg_any_Income": 0,
                        "hg_any_Profit": 0,
                        "hg_any_Cost": 0
                    },
                    {
                        "month": "12",
                        "hg_any_Income": 0,
                        "hg_any_Profit": 0,
                        "hg_any_Cost": 0
                    }
                ],
                "result": 0,
                "disOrder": [
                    "hg_any_Profit",
                    "hg_any_Income",
                    "hg_any_Cost",
                    "hg_any_Profit_all",
                    "hg_any_Income_all",
                    "hg_any_Cost_all"
                ],
                "enableSphmAlarmInfo": false,
                "flickerSwitch": false,
                "allStopWordCodeList": [],
                "photovoltaicActiveControlIsOpen": false,
                "pwrReactAutoControlIsOpen": false,
                "runbackIsOpen": false,
                "standardWTSignInSingOutIsOpen": false,
                "virtualSecurityColumn": false,
                "PwrReactAutoControlIsOpen": false,
                "StandardWTSignInSingOutIsOpen": false,
                "VirtualSecurityColumn": false,
                "UserConfig": {}
            }
        }
    }
}